[project]
name = "gates-of-hell-conquest-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Raziel090", email = "mmatusz090@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.1",
    "pyinstaller>=6.21.0",
    "ttkthemes>=3.3.0",
]

[project.scripts]
gates-of-hell-conquest-editor = "main:main"

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
